import Head from 'next/head'
import { useEffect } from 'react'
import { auth } from '../environments/firebase.utils'
import { useRouter } from 'next/router'
import { Button } from '@mui/material';
import Image from 'next/image';
import styles from '../styles/landing.module.scss';

export default function Home() {
  const router = useRouter();

  useEffect(() => {
    /*
    auth.onAuthStateChanged((user) => {
      if(user) {
        router.push("/dashboard/home")
      }
    })*/
  })

  const buttonProps = {
    textTransform: 'capitalize',
    width: '100%',
  }

  return (
    <main>
      <Head>
        <title>Quester</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav className={styles.navbar}>
          <Image height={50} width={150} src="/images/logo.svg"/>
          
          <Button variant='contained' href='/login'>
            Login
          </Button>
        </nav>
      </header>

      <section className={styles.ctaSection}>
        <div className={styles.textContainer}>
          <h1>
            Finding <span>Past Questions</span> doesn&apos;t have 
            to be headache
          </h1>

          <p>
            Quester is an app that provides you with 
            past questions within Nile Univeristy of Nigeria.
          </p>

          <div className='flex align-center justify-center'>
            <Button variant='outlined' href='/sign-up'>
              Get Started
            </Button>

            <Button variant='contained' href="#learn-more">
              Learn More
            </Button>
          </div>
        </div>

        <img src="/images/study.webp"/>
      </section>

      <section id="learn-more" className="my-30">
        <div className={styles.textContainer2}>
          <h2>
            We know how <span className="secondary">hard</span> it is to find past questions
          </h2>
          <p>So we&apos;re doing the heavy lifting for you</p>
        </div>
      </section>

      <section className='flex align-center justify-around my-30 flex-col-mobile'>
        <Image height={200} width={320} src="/images/bookshelf.svg"/>
        <div className={styles.textContainer2}>
          <h3>Search from our array of questions</h3>
          <p>No matter your department, midterm or finals, we got you.</p>
        </div>
      </section>

      <section className='flex align-center justify-around my-30 flex-col-mobile-reverse'>
        <div className={styles.textContainer2}>
          <h3>Contribute to Quester</h3>
          <p>
            You can help make Quester better 
            by adding past questions you find
          </p>
        </div>
        <Image height={200} width={320} src="/images/studying.svg"/>
      </section>

      <section className='flex align-center justify-around my-30 flex-col-mobile'>
        <Image height={200} width={320} src="/images/exams.svg"/>
        <div className={styles.textContainer2}>
          <h3>Ace your exams in style!</h3>
          <p>Who knows, your lecturer might repeat those questions</p>
        </div>
      </section>

      {
        /*
        
        <section className='flex items-center justify-center flex-col'>
  
  
          <Button variant='contained' sx={buttonProps} href='/login'>
            Login
          </Button>
  
          <Button sx={buttonProps} href='/sign-up'>
            Sign Up
          </Button>
  
        </section>
        
        */
      }

      <section>
        <div className={styles.textContainer2}>
          <h3>Produced by</h3>
          <div className={styles.gdsc}>
            <Image 
              height={200} 
              width={450}
              src="/images/gdsc_logo.svg"
            />
          </div>
        </div>
      </section>

    </main>
  )
}
